import { legalAddress, legalOperator, type LegalDraftSection } from './legal-types';

export const merchantDraft: readonly LegalDraftSection[] = [
  { id: 'parties', heading: 'Parties, agreement and order of precedence', paragraphs: [
    `These business terms are between ${legalOperator}, at ${legalAddress}, and the merchant named in a signed or expressly accepted order form. Each signatory must have authority to bind its organization. Creating a trial account or reading these terms does not execute an agreement.`,
    'The order form identifies the services, approved domains or channels, territory, term, charges, offer criteria and implementation conditions. The partner data-protection schedule governs personal-data matters; mandatory law prevails. An order form changes these standard terms only where it expressly identifies the change and both parties accept it. Student purchases remain subject to their own terms and statutory rights.',
  ] },
  { id: 'scope', heading: 'Services and activation', paragraphs: [
    'Awoof supplies only the marketplace, verification or integration services specified in the order form and confirmed as available for activation. A demonstration, roadmap item or institution email domain is not a warranty of an operational enrollment source. Production use requires the agreed configuration and completion of the applicable activation checks.',
    'The merchant supplies accurate setup information, authorized contacts and the technical resources needed for its integration. Unless expressly agreed, there is no exclusivity, minimum volume, guaranteed conversion rate, guaranteed number of students or service-level credit. Each party remains an independent business; an expressly agreed payment-collection role does not create a general agency.',
  ] },
  { id: 'results', heading: 'What a verification result permits', paragraphs: [
    'Results may be used only for the approved benefit, merchant, purpose and validity period. School-account control must not be described as current enrollment. A result is evidence of the check performed at the stated time; it is not a guarantee of identity, future enrollment, creditworthiness or purchase completion.',
    'The merchant must apply the documented server-side authorization flow and handle expired, withdrawn, unavailable and unsuccessful results correctly. Historical receipts are records of previous events and cannot be treated as fresh authority. The merchant must not override a failed enrollment check by presenting a cached result as current.',
    'Do not sell results, build a cross-merchant identity graph, re-identify a scoped identifier, enrich unrelated advertising profiles, train a model on personal verification records, or use results for credit, insurance, employment or another unrelated consequential decision. Any materially different purpose requires a separate approved service, lawful basis and agreement.',
  ] },
  { id: 'offers', heading: 'Offers, customer obligations and permitted products', paragraphs: [
    'The merchant is responsible for lawful, accurate offers; stock; displayed prices and exclusions; product safety and authenticity; fulfilment; warranties; taxes for its supply; complaints; and legally required refunds. It must honor a qualifying purchase on the conditions presented when accepted and correct an expired or misleading listing promptly.',
    'The merchant must not use Awoof to promote unlawful goods, deceptive offers or products requiring an age or licence check that the integration does not perform. A student result is not an age-verification result. The merchant must not imply university endorsement, an exclusive relationship or an Awoof guarantee without written permission.',
  ] },
  { id: 'payments', heading: 'Fees, collection, settlement and disputed payments', paragraphs: [
    'Fees, commission, billing units, taxes, payment-provider charges and settlement arrangements must be specified in the order form before they apply. There is no implied commission rate, automatic renewal or entitlement to a future volume discount. A trial’s end and any move to paid use require the agreed notice and acceptance.',
    'For merchant-hosted checkout, the merchant maintains its payment arrangements. For an Awoof-initiated checkout, the payment schedule must identify the seller and payee, Awoof’s collection role if any, split or manual settlement, reconciliation timing, refund authority, chargeback handling and responsibility for provider costs. These terms alone do not appoint Awoof as an unrestricted collection agent or promise a settlement date.',
    'Each party must supply records reasonably needed to reconcile a disputed transaction. A party must not retain money to which it is not entitled. Any reserve, suspension of settlement, recovery from later settlement or set-off must be expressly authorized by the payment schedule and lawful; it must be supported by the relevant records and must not extinguish customer rights.',
  ] },
  { id: 'security', heading: 'Access, credentials and security cooperation', paragraphs: [
    'The merchant must protect private keys, restrict access to authorized personnel, follow documented integration requirements, rotate compromised credentials and promptly report suspected misuse. Private credentials must remain on the merchant’s trusted server. Unauthorized testing, circumvention, bulk extraction and use outside agreed limits are prohibited.',
    'Both parties must cooperate reasonably to contain a confirmed or suspected incident. Awoof may suspend a key or integration when reasonably necessary to protect users, comply with law or prevent material misuse, with notice and a route to restoration where practicable. Suspension is limited to what is reasonably necessary and does not authorize indefinite withholding of unrelated funds.',
  ] },
  { id: 'data', heading: 'Personal information and confidentiality', paragraphs: [
    'The partner data-protection schedule and completed processing annex apply before personal data is exchanged. Each party is responsible for the legal grounds and notices for processing it controls. A commercial licence to the service is not permission to use personal data for every business purpose.',
    'Non-public business, technical and personal information disclosed for the engagement must be used only for the engagement, protected with appropriate care and disclosed only to people who need it and are bound by confidentiality. Exceptions cover information independently developed, already lawfully known, public without breach or lawfully received from another source. Legally compelled disclosure must be limited and notified where permitted.',
  ], links: [{ href: '/legal/data-protection', label: 'Read the partner data-protection schedule' }] },
  { id: 'ownership', heading: 'Ownership, branding and publicity', paragraphs: [
    'Each party retains its existing intellectual property. Awoof grants the limited, non-exclusive right to use the contracted service during the agreed term. The merchant grants the limited right to display approved offer materials and branding to deliver the agreed campaign. Neither grant transfers ownership or permits unrelated reuse.',
    'A public case study, partnership announcement or use of either party’s name as an endorsement requires prior written approval. At termination, brand use ends except for lawful historical records and the limited period reasonably needed to remove a published campaign. Open-source rights and statutory exceptions remain unaffected.',
  ] },
  { id: 'warranties', heading: 'Commitments and limits of the service', paragraphs: [
    'Each party promises that it has authority to enter the agreement and will perform its obligations with reasonable care and skill. The merchant warrants its authority to supply its offer materials and any data it provides. Awoof will supply the agreed functionality subject to the documented source and integration limitations.',
    'Awoof does not warrant uninterrupted availability, error-free external records, universal institutional coverage or a particular commercial return. This does not excuse failure to meet an expressly agreed obligation or a liability the law does not allow the parties to exclude.',
  ] },
  { id: 'claims', heading: 'Third-party claims and their defence', paragraphs: [
    'The merchant will indemnify Awoof against reasonable, established third-party losses caused by the merchant’s unlawful products, misleading offers, infringement in merchant-supplied materials, or use of personal data outside the agreed purpose. The obligation does not cover loss caused by Awoof’s own breach, negligence or unlawful act.',
    'Awoof will defend a claim that the unmodified contracted Awoof service infringes a third party’s intellectual-property rights and meet amounts awarded or settled with its approval, subject to the liability provisions. This excludes a claim caused by unauthorized merchant modifications, prohibited use or a combination that alone creates the infringement. Awoof may obtain rights, modify or replace the affected functionality, or end the affected service and refund unused prepaid service fees if those remedies are not reasonably available.',
    'The indemnified party must notify the other promptly, preserve relevant evidence and give reasonable cooperation. Delay reduces protection only to the extent it causes prejudice. The defending party may control a competent defence, but cannot admit liability for the other party or impose a non-monetary obligation without its written agreement. Neither party may recover the same loss twice.',
  ] },
  { id: 'liability', heading: 'Business liability limits', paragraphs: [
    'Subject to the exceptions below and any expressly negotiated alternative, each party’s aggregate liability arising from a paid order is capped at the service fees paid or payable under that order for the twelve months before the event giving rise to the claim. Purchase proceeds held for the other party are not service fees. For a free pilot, the parties must agree a reasonable cap expressly; no zero-liability cap is implied.',
    'For confidentiality breaches, breach of the data-protection schedule and the third-party indemnities, the aggregate cap is twice that fee amount unless a different amount is expressly agreed. Losses too remote under applicable law and indirect commercial losses are excluded to the extent legally permitted. These allocations require express agreement before execution.',
    'No cap or exclusion applies to fraud, fraudulent misrepresentation, gross negligence, wilful misconduct, payment or remittance obligations, or liability that cannot lawfully be limited. No agreement between the parties restricts a regulator’s powers or a data subject’s or consumer’s statutory rights. Any allocation of responsibility between the parties for such claims must itself be lawful.',
  ] },
  { id: 'term', heading: 'Term, termination and exit', paragraphs: [
    'The order form states the start, duration and any renewal procedure. Either party may end the affected order for a material breach not remedied within thirty days after a notice describing it, or sooner where the breach cannot be remedied or continued performance would be unlawful. Urgent protective suspension may occur under the security section.',
    'At termination, new use of the service and branding ends. The parties must reconcile accrued fees, customer refunds and settlement amounts; complete agreed data return or deletion; and cooperate on a reasonable exit that does not mislead customers. Prepaid fees for a period Awoof cannot provide because of its unremedied material breach are refundable. Other early-exit charges require express agreement.',
    'Provisions concerning accrued payments, confidentiality, ownership, lawful records, claims, liability and disputes survive to the extent necessary for their purpose.',
  ] },
  { id: 'disputes', heading: 'Notices, disputes and general provisions', paragraphs: [
    'Legal notices go to the contacts in the order form, with Awoof notices copied to support@awoof.tech. The parties will first seek resolution through their designated representatives where practicable. Nigerian law governs, and courts of competent jurisdiction in Nigeria may hear disputes, subject to mandatory law and any separately negotiated lawful dispute agreement. Either party may seek urgent protective relief.',
    'A delay beyond a party’s reasonable control requires prompt notice and reasonable mitigation; it does not excuse accrued remittance, confidentiality or statutory obligations. If it materially prevents performance, the parties should agree a revised timetable or end the affected service and reconcile unused fees. Changes require written agreement. Assignment requires the other party’s consent, not unreasonably withheld, except a lawful business transfer with notice and adequate protection for accrued rights. An unenforceable provision is severed only so far as the remaining agreement can operate lawfully.',
  ] },
];
