'use client';

import { useState } from 'react';
import { AuthShell } from '@/components/auth/AuthShell';
import { Button } from '@/components/ui/button';
import { publicApiClient } from '@/lib/api-client';

export default function StudentAccountRecoveryPage() {
    const [email, setEmail] = useState(''); const [compromise, setCompromise] = useState(false); const [sent, setSent] = useState(false); const [error, setError] = useState<string | null>(null); const [attempt, setAttempt] = useState<{ id: string; secret: string } | null>(null); const [recoveryCode, setRecoveryCode] = useState(''); const [otp, setOtp] = useState(''); const [verified, setVerified] = useState(false); const [password, setPassword] = useState('');
    const start = async (event: React.FormEvent) => { event.preventDefault(); setError(null); try { const r = await publicApiClient.post('/auth/student/sso/account-recovery/start', { email, purpose: compromise ? 'compromise' : 'lost_access' }); const data = (r.data as { data?: { attemptId?: unknown; secret?: unknown } }).data; if (typeof data?.attemptId !== 'string' || typeof data.secret !== 'string') throw new Error('invalid'); setAttempt({ id: data.attemptId, secret: data.secret }); setSent(true); } catch { setError('Recovery could not be started. Check the details and try again.'); } };
    const verify = async (event: React.FormEvent) => { event.preventDefault(); if (!attempt) return; setError(null); try { await publicApiClient.post('/auth/student/sso/account-recovery/verify', { attemptId: attempt.id, secret: attempt.secret, code: recoveryCode, otp }); setRecoveryCode(''); setOtp(''); setVerified(true); } catch { setError('Recovery proof could not be confirmed. Start again if the attempt expired.'); } };
    const complete = async (event: React.FormEvent) => { event.preventDefault(); if (!attempt) return; setError(null); try { await publicApiClient.post('/auth/student/sso/account-recovery/complete', { attemptId: attempt.id, secret: attempt.secret, password }); setAttempt(null); setPassword(''); setVerified(false); setSent(false); setError('Password set. Sign in with your password to continue.'); } catch { setError('Password setup could not be completed. Start recovery again if the attempt expired.'); } };
    return <AuthShell role="student" title="Account recovery" subtitle="Use this only if you cannot use school sign-in." footer={null}>
        {verified ? <form onSubmit={complete} className="space-y-3 text-left"><p className="text-sm">Set an optional password, then sign in normally. This recovery does not grant enrollment eligibility.</p><label htmlFor="recovery-password">New password<input id="recovery-password" type="password" value={password} onChange={e => setPassword(e.target.value)} className="mt-1 w-full rounded-2xl border px-4 h-11" /></label>{error ? <p role="alert" className="text-sm text-red-600">{error}</p> : null}<Button type="submit" className="w-full rounded-full">Set password</Button></form> : sent ? <form onSubmit={verify} className="space-y-3 text-left"><p role="status" className="text-sm">If this account can use recovery, enter both the saved recovery code and the email confirmation code. Sign in with your password afterward.</p><label htmlFor="saved-code">Saved recovery code<input id="saved-code" value={recoveryCode} onChange={e => setRecoveryCode(e.target.value)} className="mt-1 w-full rounded-2xl border px-4 h-11" /></label><label htmlFor="mailbox-otp">Email confirmation code<input id="mailbox-otp" value={otp} onChange={e => setOtp(e.target.value)} className="mt-1 w-full rounded-2xl border px-4 h-11" /></label>{error ? <p role="alert" className="text-sm text-red-600">{error}</p> : null}<Button type="submit" className="w-full rounded-full">Confirm recovery proofs</Button></form> : <form onSubmit={start} className="space-y-4 text-left"><p className="text-sm text-slate-600">Recovery requires your school mailbox and saved recovery code. Mailbox access alone never transfers account ownership. If you no longer have both, contact the monitored support channel; support cannot bypass this proof.</p><label className="block text-sm font-medium" htmlFor="recovery-email">School email<input id="recovery-email" aria-label="School email" type="email" required value={email} onChange={e => setEmail(e.target.value)} className="mt-1 w-full rounded-2xl border px-4 h-11" /></label><label className="flex gap-2 text-sm"><input aria-label="I think my sign-in was compromised" type="checkbox" checked={compromise} onChange={e => setCompromise(e.target.checked)} />I think my sign-in was compromised</label>{compromise ? <p role="alert" className="text-sm text-amber-700">Completing this recovery will disconnect all linked external sign-in identities. Secure your Microsoft account and mailbox too; Awoof cannot revoke their sessions.</p> : <p className="text-sm text-slate-600">Lost-access recovery keeps linked school sign-ins connected when they remain available.</p>}{error ? <p role="alert" className="text-sm text-red-600">{error}</p> : null}<Button type="submit" className="w-full rounded-full">Start recovery</Button></form>}
    </AuthShell>;
}
